# RENAME COMMAND

USE MYDB;

# CREATING NEW TABLE
CREATE TABLE TEACH
(TID INT(4), TNAME VARCHAR(15));
DESCRIBE TEACH;

# INSERTING DATA INTO THE TABLE
INSERT INTO TEACH VALUES (201, 'PAVAN');
INSERT INTO TEACH VALUES (202, 'ALEX');
RENAME TABLE TEACH TO TEACHER;

DESCRIBE TEACHER;
SELECT * FROM TEACHER;

