# WHERE KEYWORD
# WHERE KEYWORD

USE WORLD;

SELECT * FROM COUNTRY;
SELECT * FROM COUNTRY WHERE POPULATION > 1500000;
SELECT * FROM COUNTRY WHERE POPULATION < 1500000;
SELECT * FROM COUNTRY WHERE CONTINENT = 'NORTH AMERICA';
SELECT * FROM COUNTRY WHERE INDEPYEAR IS NULL;

SELECT * FROM COUNTRY WHERE NAME = 'BANGLADESH';
SELECT * FROM COUNTRY WHERE INDEPYEAR = 1960;
SELECT DISTINCT INDEPYEAR FROM COUNTRY;	# DISTNCT KEYWORD IS USED TO GET UNIQUE ID'S. NO DUPLICATE DATA WILL BE SHOWN
SELECT DISTINCT * FROM COUNTRY;
