# PATTERN MATCHING OPERATORS
# PATTERN MATCHING OPERATORS

USE WORLD;
SELECT * FROM COUNTRY;
SELECT NAME FROM COUNTRY WHERE NAME LIKE 'S%';	# NAME STARTED WITH S
SELECT NAME FROM COUNTRY WHERE NAME LIKE '%R';	# NAME THAT ENDED WITH R
SELECT NAME FROM COUNTRY WHERE NAME LIKE 'S%A';	# NAME STARTED WITH S & ENDED WITH A
SELECT NAME FROM COUNTRY WHERE NAME LIKE '%M%';	# NAME STARTED & ENDED WITH ANY LETTER, BUT SOMEWHERE IN THE MIDDLE IT HAS M

SELECT NAME FROM COUNTRY WHERE NAME NOT LIKE 'S%';	# NAME THAT DIDN'T START WITH S
SELECT * FROM COUNTRY WHERE NAME LIKE '%S_';	# NAME THAT STARTED WITH MANY LETTERS ENDED WITH ONLY ONE LETTER AFTER S
SELECT * FROM COUNTRY WHERE NAME LIKE '___';	# NAME THAT STARTED WITH ONLY THREE LETTERS
# '_' representing one character
# '%' representing many chracters
show columns from city;







