# DELETE COMMAND
# ROLLBACK COMMAND 
# COMMIT COMMAND

USE MYDB;
SELECT * FROM STUDENT;

SET AUTOCOMMIT = 0;		# IT WON'T COMMIT AUTOMATICALLY FOR DELETE COMMAND. IF IT IS NOT SET TO '0', IT DELETES DATA PERMANENTLY.
SET SQL_SAFE_UPDATES = 0;	# IT'LL ALLOW TO UPDATE THE TABLE DATA
DELETE FROM STUDENT;
SELECT * FROM STUDENT;	# DATA DELETED 

ROLLBACK;
SELECT * FROM STUDENT;	# DATA RETURNED BECAUSE OF ROLLBACK COMMAND, AS AUTOCOMMIT SET TO '0' - IT DOESN'T DELETE DATA PERMANENTLY.

# TO DELETE DATA PERMANENTLY
DELETE FROM STUDENT;
SELECT * FROM STUDENT;	# DATA DELETED 
COMMIT;		# COMMIT DOES EVERYTHING AS THE COMMANDS SAID, IN THIS CASE COMMIT DELETES EVERY DATA PERMANENTLY.




